import { test as myTest } from "@playwright/test"

type myFixture = {
  userName: string
  textProject: string,
  obsProject: string,
  audioProject: string,
  syncName: string,
  doorUser: string,
  doorPassword: string,
  flavorText: string,
  flavorObs: string
  textUnderscore: string,
  obsUnderscore: string,
  customTextProject: string,
  customObsProject: string,
  customAudioProject: string,
  projectObsType: string,
  projectAudioType: string,
  description: string,
  textAbbreviation: string,
  obsAbbreviation: string,
  AudioAbbreviation: string,
  starProject: string,
  unstarProject: string,
  currentLicense: string,
  newLicense: string,
  customTextLanguage: string,
  customObsLanguage: string,
  customAudioLanguage: string,
  english: string,
  hindi: string
}
const myFixtureTest = myTest.extend<myFixture>({
  userName: "Playwright user",
  textProject: "Translation test project",
  obsProject: "Obs test project",
  projectObsType: "OBS",
  projectAudioType: "Audio",
  description: "test description",
  textAbbreviation: "ttp",
  obsAbbreviation: "otp",
  AudioAbbreviation: "atp",
  starProject: "star-project",
  unstarProject: "unstar-project",
  currentLicense: "CC BY-SA",
  newLicense: "CC BY",
  customTextProject: "Custom text transaltion project",
  customObsProject: "Custom obs project",
  customAudioProject: "Custom audio project",
  customTextLanguage: "custom text translation language",
  customObsLanguage: "custom obs project language",
  customAudioLanguage: "custom audio project language",
  english: "English",
  hindi: "Hindi",
  textUnderscore: "Translation_test_project",
  obsUnderscore: "Obs_test_project",
  audioProject: "Audio test project",
  syncName: "Sync_Collab_Test",
  doorUser: "bobby",
  doorPassword: "Bobby@123",
  flavorText: "textTranslation",
  flavorObs: "textStories",
})

export const test = myFixtureTest;
export { expect } from '@playwright/test';